"""accident upd

Revision ID: 5df5e21b5560
Revises: e795fc8b196f
Create Date: 2024-07-15 17:52:21.090871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5df5e21b5560'
down_revision = 'e795fc8b196f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accident', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('accident', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('accident', sa.Column('building_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accident', 'building_id')
    op.drop_column('accident', 'longitude')
    op.drop_column('accident', 'latitude')
    # ### end Alembic commands ###
