"""subject with statuses

Revision ID: 5f6bf4ab7425
Revises: bfc8c9223afa
Create Date: 2024-07-27 21:05:05.714732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f6bf4ab7425'
down_revision = 'bfc8c9223afa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
