"""accident: nodes

Revision ID: 6b88e0a9b418
Revises: 71e3925a6987
Create Date: 2024-07-24 17:42:03.501001

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6b88e0a9b418'
down_revision = '71e3925a6987'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accident', sa.Column('nodes', postgresql.ARRAY(sa.Float()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accident', 'nodes')
    # ### end Alembic commands ###
