"""subject with statuses

Revision ID: 8934403c5f6f
Revises: 5f6bf4ab7425
Create Date: 2024-07-27 21:45:09.205159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8934403c5f6f'
down_revision = '5f6bf4ab7425'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
