"""created_by on Accident

Revision ID: ad611f0aeef5
Revises: 3a711c7ea897
Create Date: 2024-07-23 18:06:46.699085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad611f0aeef5'
down_revision = '3a711c7ea897'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accident', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'accident', 'user', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accident', type_='foreignkey')
    op.drop_column('accident', 'created_by')
    # ### end Alembic commands ###
